### ISSUE TITLE
multiple same-name headings have same id

### ISSUE THREAD

**Issue by KristerV** [stubailo/meteor-markdown-templating#1]
Hey.

If I have two headings with the same name, then both of them will have the same id. Though everything works, it's hard to manage content in some cases. How could I add an index on top of these id's?
# Meteor.js
## Getting started
# Node.js

**Comment by KristerV** [comment]
sorry, i understand this is a meteor/markdown issue.

**Comment by stubailo** [comment]
Yeah, sorry, can't really help you there.

I think you can get around it by using HTML tags directly, but it's not pretty:

```
<h2 id="getting-started-1">Getting started</h2>
<h2 id="getting-started-2">Getting started</h2>
```

**Comment by KristerV** [comment]
yep, decided to ditch markdown completely and go with jade for my project.
