### ISSUE TITLE
Question: how to markdown spacebars?

### ISSUE THREAD

**Issue by kokjinsam** [stubailo/meteor-markdown-templating#4]
Hi,

I tried to markdown the following and couldn't succeed marking down spacebars:

```
{{#template name="markdownBody"}}

  <template name="yourTemplate">
    {{#fixedDrawer args 200 options}}
      Your content
    {{/fixedDrawer}}
  </template>

{{/template}}
```

Any guidance on this would be very much appreciated! Thanks!

**Comment by stubailo** [comment]
I think it would just work if you did this:

```
{{#template name="yourTemplate"}}
    {{#fixedDrawer args 200 options}}
      Your content
    {{/fixedDrawer}}
{{/template}}
```

**Comment by kokjinsam** [comment]
I'm sorry I meant this: 

```
{{#template name="markdownBody"}}

##Syntax
` ` `
  <template name="yourTemplate">
    {{#fixedDrawer args 200 options}}
      Your content
    {{/fixedDrawer}}
  </template>
` ` `

{{/template}}
```

I want to show the spacebar code like how GitHub markdown displays spacebar code.

**Comment by stubailo** [comment]
Ohh, yeah is your problem that it's parsing the `{{` tags?

In that case you can declare a global helper that just returns `"{{"` and use the helper; you might also be able to use the HTML entities for the brackets.

**Comment by kokjinsam** [comment]
Thanks a lot! Got it worked now!
