### ISSUE TITLE
Md template in a collection

### ISSUE THREAD

**Issue by hsduk** [stubailo/meteor-markdown-templating#5]
Hi
I envisage having many templates. 
Q/FR: Is it possible to store the md template text in a collection and not on the fs? This will help managing many templates easy.
Thx

**Comment by stubailo** [comment]
Yeah - this package is specifically for having pre-compiled templates as part of your app source code. If you want to render markdown strings, you should just use the built-in markdown package: http://docs.meteor.com/#/full/markdown
