### ISSUE TITLE
Help bringing package up-to-date

### ISSUE THREAD

**Issue by pferrel** [stubailo/meteor-markdown-templating#6]
I've found a few bugs to do with code including quotes and trying to embed XML as code. I'd like to fix these but need to start simpler.

I'm a complete noob so thought I'd start with making the package fit the latest Meteor definition. Can you point me in the right direction here? not sure what version of packages the current code was written to or what the difference might be.

Also @stubailo you mentioned "modify the package to avoid the template tags" by which you mean the {{#template name='template-name'}}{{/template}}? If so what was your idea? Some form of template naming and begin/end is needed, right? I even keep 2 in one file with this method.

Any guidance would be appreciated. Or suggestions for something else to tackle, something a little on the easy side to start with?

**Comment by stubailo** [comment]
Hmm, I think this package isn't a great place for a noob to start because it's a build plugin - those are rather complicated in Meteor. Especially the new build plugin interface with caching is a bit hard.

We would need to modify the package to be similar to: https://github.com/meteor/meteor/blob/devel/packages/templating/plugin/compile-templates.js

Except, we would replace `scanHTMLForTags` with our own thing.

**Comment by pferrel** [comment]
OK I'll take a look. The difference between a noob and an expert is a lot of banging your head on a wall and I've been known to do this. We'll see.

If I'm unable to fix my problem perhaps you have a work around?

XML is parsed inside of code blocks and I have found no way to have it ignored. This usually results in blank spaces since the XML is undefined in HTML5.  The other worse outcome is the page is unparsable, which means the entire page is not shown. XML examples, which are key to my content, are quite problematic. I don't mind popping out to HTML so I'll see if there is a solution there.

**Comment by stubailo** [comment]
> inside of code blocks

Do you mean inside of the triple-backtick code fences?

Anyway, unfortunately I don't really use this package anymore (I'm moving my markdown content into static sites) so I probably can't actually fix the problem, but I'm happy to answer questions.

**Comment by pferrel** [comment]
it looks like it's a styling issue, if I use triple backticks and specify xml as the highlight language everything is marked up with HTML correctly but styles mess up the display.

Will continue to investigate the new build plugin interface, thanks.

**Comment by abernix** [comment]
This should be fixed with #8. ;)
